Vagrant.configure("2") do |config|
    config.ssh.insert_key = true  # Gera chaves SSH automaticamente.
    config.vm.boot_timeout = 600  # Aumenta o tempo de espera para inicialização.
  
    # Máquina Debian
    config.vm.define "debian" do |debian|
      debian.vm.box = "debian/bullseye64"  # Imagem base do Debian.
      debian.vm.network "private_network", ip: "192.168.56.101"  # Rede privada com IP fixo.
      debian.vm.hostname = "debian.lab.local"  # Nome da máquina.
      debian.vm.synced_folder "./debian_files", "/home/vagrant/sync", create: true  # Pasta sincronizada.
      debian.vm.provision "shell", path: "scripts/debian.sh"  # Script de provisionamento.
      debian.vm.provider "virtualbox" do |vb|
        vb.name = "Debian-VM-Lab"  # Nome na interface do VirtualBox.
        vb.memory = 1024  # Memória RAM.
        vb.cpus = 2  # CPUs.
      end
    end
  
    # Máquina AlmaLinux
    config.vm.define "almalinux" do |almalinux|
      almalinux.vm.box = "almalinux/8"
      almalinux.vm.network "private_network", ip: "192.168.56.102"
      almalinux.vm.hostname = "almalinux.lab.local"
      almalinux.vm.synced_folder "./almalinux_files", "/home/vagrant/sync", create: true
      almalinux.vm.provision "shell", path: "scripts/almalinux.sh"
      almalinux.vm.provider "virtualbox" do |vb|
        vb.name = "AlmaLinux-VM-Lab"
        vb.memory = 1024
        vb.cpus = 2
      end
    end
  
    # Máquina Windows Server
    config.vm.define "windows" do |windows|
      windows.vm.box = "mcree/win2019"
      windows.vm.network "private_network", ip: "192.168.56.103"
      windows.vm.hostname = "windows-lab.local"
      windows.vm.synced_folder "./windows_files", "C:\\sync", create: true
      windows.vm.provision "shell", path: "scripts/windows.ps1"
      windows.vm.provider "virtualbox" do |vb|
        vb.name = "Windows-VM-Lab"
        vb.memory = 2048
        vb.cpus = 2
      end
      windows.vm.communicator = "winrm"  # Usar WinRM para comunicação.
      windows.winrm.username = "Administrator"
      windows.winrm.password = "Admin@Super"
    end
  end
  